### ISSUE TITLE
Pre-selected date needed

### ISSUE THREAD

**Issue by thesmallestgnome** [pkaske/pk-datepicker#1]
It would be nice to be able to set some particular date, say 1 of April 2015

**Comment by trading-peter** [comment]
Actually, I plan to implement that in the near future. Stay tuned ;)

**Comment by trading-peter** [comment]
Version 2.0.0 of the component is out.
I removed the `day` and `month` properties. If you were relaying on them, be sure to check out the new `date` property. This is also the property to pre-select a date.
The `date-selected` event should behave as before.
I added a live demo hosted on github (see readme).
