### ISSUE TITLE
Navigate through the years

### ISSUE THREAD

**Issue by rubenstolk** [pkaske/pk-datepicker#4]
Suppose I was born in 1975 and I have to choose my DoB, in current scenario I'll have to click 40 times. Any idea of how to improve this?

**Comment by trading-peter** [comment]
Check out version 3.0.1. I just released it and made some improvements.
- Icons are now injected via `content` elements. See the updated demo for example code.
- You can now click the year or month to show a selection list. This enables you to quickly jump between months or years.

**Comment by rubenstolk** [comment]
You're awesome.

## 

BR, Ruben Stolk
+919561050034  |  +31646118037

On Mon, Jun 29, 2015 at 5:40 AM -0700, "Peter Kaske" notifications@github.com wrote:

Check out version 3.0.0. I just released it and made some improvements.

Icons are now injected via content elements. See the updated demo for example code.
You can now click the year or month to show a selection list. This enables you to quickly jump between months or years.
